config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users

  get '/users/:id', to: 'users#show'
  get '/feed', to: 'users#feed'
  get '/friends', to: 'users#friends'
  get '/users', to: 'users#index'
  
  post '/follows', to: 'follows#create'
  delete '/follows', to: 'follows#destroy'

  root 'books#index'

  resources :books do
      resources :reviews, except: [:show, :index]
  end
  
  get '/about', to: 'about#index'

end

app/views/shared/_activity.html.erb
<% @activityUser  = User.find(activity.user_id) %>
<% @activityBook  = Book.find(activity.book) %>

<div class="col-sm-4">
    <%= image_tag @activityBook.image_url, class: "book-show center-block" %> 
</div>
<div class="col-sm-8">
      <h4><a href="/books/<%=@activityBook.id%>"><%= @activityBook.title %></a></h4>
      <p>By <a href="https://book-keeper-jamesqquick.c9users.io/books/new/?q=<%=@activityBook.author%>"><%= @activityBook.author %></a></p>

      <p><%=activity.list_type %> by <a href="users/<%= @activityUser.id %>"><%= @activityUser.username %></a> <%= time_ago_in_words(activity.updated_at) %> ago</p>
</div>

app/views/shared/_book.html.erb
<div class="col-md-3 col-sm-6">
    <a href="/books/<%=book.id%>" data-toggle="modal">
        <div class="book-hover">
            <div class="book-hover-content">
                <p>View Book</p>
            </div>
        </div>
        <%= image_tag  book.image_url, class: "book" %>  
    </a>
</div>

app/views/shared/_book_details.html.erb
<div class="col-md-4">
    <%= image_tag book.image_url(), class: "book-show center-block" %> 
</div>
<div class="col-md-7">
    <h3><%= book.title %></h3>
    <p>By <a href="https://book-keeper-jamesqquick.c9users.io/books/new/?q=<%=book.author%>"><%= book.author %></a></p>
    <p><%= book.description %></p>
    <% if user_signed_in? && !@review.id.present? %>
        <%= link_to "Add Review", new_book_review_path(@book), class: "btn btn-primary" %>     
    <% end %>
    <% if user_signed_in? %>
        <% @newBook = Book.new %>
        <% if UserBook.where(book_id: book.id, user_id: current_user.id, list_type:"read").empty?  %>
              <%= simple_form_for @newBook do |f| %>
                <%= f.hidden_field :title,           :value => book.title %>
                <%= f.hidden_field :author,          :value => book.author %>
                <%= f.hidden_field :description,     :value => book.description %>
                <%= f.hidden_field :image_url,       :value => book.image_url %>
                <%= f.hidden_field :isbn,            :value => book.isbn %>
                <%= f.button :submit, "Read", class: "btn-primary btn", name: "type", value: "read" %>
              <% end %>
        <% end %>
        
        <% if UserBook.where(book_id: book.id, user_id: current_user.id, list_type:"queue").empty?  %>
            <%= simple_form_for @newBook do |f| %>
                  <%= f.hidden_field :title,           :value => book.title %>
                  <%= f.hidden_field :author,          :value => book.author %>
                  <%= f.hidden_field :description,     :value => book.description %>
                  <%= f.hidden_field :image_url,       :value => book.image_url %>
                  <%= f.hidden_field :isbn,            :value => book.isbn %>
                  <%= f.button :submit, "Add To Queue", class: "btn-primary btn", name: "type", value: "queue" %>
              <% end %>
          <% end %>
      <% end %>

</div> 

app/views/shared/_book_list.html.erb
<% books.each do |book| %>
    <div class="col-xs-3">
         <a href="/books/<%=book.id%>">
            <%=image_tag  book.image_url, class: "book center-block" %>    
        </a>  
    </div>
<% end %>

app/views/shared/_edit_book.html.erb
<div class="edit-book">
    <% if false %> <%# Only give admins the right to delete the books %>
        <% if user_signed_in? %>
            <% if @book.user_id == current_user.id %>
                <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_book_path(@book), class: "btn book-btn"  %>
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, book_path(@book), method: :delete, data: {confirm: "Are you sure" }, class: "btn book-btn"  %>
            <% end %>
        <% end %> 
    <% end %> 
    <% if !@review.id.present? %>
        <%= link_to "Add Review", new_book_review_path(@book), class: "btn btn-primary" %>     
    <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this book from being created.
                        
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <%= obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="container">
    <div class="row">
        <div class="">
            <% flash.each do |name, msg| %>
                <% if msg.include? "Invalid" %>
                    <% name = "danger" %>
                <% else %>
                    <% name = "success" %>
                <% end %>
                <% puts "alert-#{name}" %>
                <div class='alert <%= "alert-#{name}" %>'>
                    <a href="#" class="close" data-dismiss="alert">x</a>
                    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                </div>
            <% end %>
        </div>
    </div>
    
</div>

app/views/shared/_new_book_options.html.erb
<% if user_signed_in? %>

    <% if UserBook.where(isbn: book.isbn, user_id: current_user.id, list_type:"read").empty?  %>

          <%= simple_form_for @book do |f| %>
              <%= f.hidden_field :title,           :value => book.title %>
              <%= f.hidden_field :author,          :value => book.authors_array.first %>
              <%= f.hidden_field :description,     :value => book.description %>
              <%= f.hidden_field :image_url,       :value => book.image_link %>
              <%= f.hidden_field :isbn,            :value => book.isbn %>
              <%= f.button :submit, "Read", class: "btn-primary btn", name: "type", value: "read" %>
          <% end%>
    <% else %>
      <p><small>You've already read this book</small></p>
    <% end %>
     
     <% if UserBook.where(isbn: book.isbn, user_id: current_user.id, list_type:"queue").empty?  %>
      
          <%= simple_form_for @book do |f| %>
              <%= f.hidden_field :title,           :value => book.title %>
              <%= f.hidden_field :author,          :value => book.authors_array.first %>
              <%= f.hidden_field :description,     :value => book.description %>
              <%= f.hidden_field :image_url,       :value => book.image_link %>
              <%= f.hidden_field :isbn,            :value => book.isbn %>
              <%= f.button :submit, "Add To Queue", class: "btn-primary btn", name: "type", value: "queue" %>
          <% end %>
    <% else %>
      <p><small>You've already queued this book</small></p>
    <% end %>
<% end %>

app/views/shared/_user_details.html.erb
<div class="user-details col-sm-3">
    <h4><a class="text-center" href="/users/<%=user.id%>"><p>@<%= user.username %></p></a></h4>
    <p class="text-center" >Read <%= user.books.count %> books </p> 
    <p class="text-center"> <%= pluralize(user.followers.count, "Follower")%> | Following <%= user.all_following.count%></p>

    <% if user_signed_in? %>
        <% if !current_user.following?(user) %>
            <%= simple_form_for @follow do |f| %>
                <%= f.hidden_field :follable_id,   :value => user.id %>
                <%= f.button :submit, "Follow", class: "btn-success btn btn-xs center-block" %>
            <% end %>
        <% else %>
            <%= simple_form_for(@follow, :html => {:method => 'delete'})  do |f|  %>
                <%= f.hidden_field :follable_id,   :value => user.id %>
                <%= f.button :submit, "Unfollow", class: "btn-danger btn btn-xs center-block" %>
            <% end %>
        <% end %>
    <% end %>

</div>  