config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users

  get '/users/:id', to: 'users#show'
  get '/feed', to: 'users#feed'
  get '/friends', to: 'users#friends'
  get '/users', to: 'users#index'
  
  post '/follows', to: 'follows#create'
  delete '/follows', to: 'follows#destroy'

  root 'books#index'

  resources :books do
      resources :reviews, except: [:show, :index]
  end
  
  get '/about', to: 'about#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :user
    has_many :reviews
    has_many :user_books, dependent: :destroy
    has_many :users, through: :user_books
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    before_action :find_book , only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]
    
    def index
        redirect_to feed_path if current_user
        #Get all the most recently read books regardless of who read them
        @books = UserBook.all.order("created_at DESC").take(4)
    end
    
    def new
        @book = Book.new

        if params[:q].nil?
        else
            #Search Google Books
            @unfilteredSearchBooks = GoogleBooks.search(params[:q], {:count => 10})
            #Filter by books that have an ISBN Number
            @searchBooks = @unfilteredSearchBooks.select  {|book| book.isbn.present?}
        end
    end
    
    def create
        # If the book has not been created, then create it
        # Either retrieve the book or create it, then add an association between user and book in UserBook table
        @book = Book.where(isbn: params[:book][:isbn]).first
        if @book
            @userBook = UserBook.create(user_id: current_user.id, book_id: @book.id, isbn: @book.isbn, list_type: params[:type])
            if @userBook.save
                redirect_to new_book_path
            else
                redirect_to new_book_path
            end
        #Else create the book and then the association
        else
            @book = Book.new(book_params)
            if @book.save
                #how to add the type parameter?
                @userBook = UserBook.create(user_id: current_user.id, book_id: @book.id, isbn: @book.isbn, list_type: params[:type])
                @userBook.save
                redirect_to new_book_path
            else
                redirect_to new_book_path
            end          
        end

    end
    
    def show
            @reviews = @book.reviews.order("updated_at DESC")
        if current_user
            #Check to see if the user has already reviewed this book
            @review = @book.reviews.where(user_id: current_user.id).first_or_initialize
        end
    end
    
    
    def edit
    end
    
    def update
        @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            redirect_to 'edit'
        end
    end
    
    def destroy
        if @book.destroy
            redirect_to root_path
        else
            render 'show'
        end
    end
    
    private
        def book_params
            params.require(:book).permit(:title, :author, :description, :category_name, :image_url, :isbn, :list_type)
        end
        
        def find_book
            @book = Book.find(params[:id])
        end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>  
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/books/_review.html.erb
<div class="review">
    <div class="star-rating" data-score=<%= review.rating %> ></div>
    <p><%= "#{distance_of_time_in_words_to_now(review.updated_at)} ago by @#{review.user.username}" %></p>
    <p><%=review.comment %></p>

    <% if user_signed_in? %>
        <% if current_user.id == review.user_id %>
            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_book_review_path(@book, review), class: "btn "  %>
            <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, book_review_path(@book, review), method: :delete, data: {confirm: "Are you sure" }, class: "btn " %>
        <% end %>
    <% end %>
    <hr>    
</div>

app/views/books/_search_book_modal.html.erb
<div class="modal fade" id="book-<%=book.isbn%>" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
    
                    <div class="col-sm-4">
                        <%=image_tag  book.image_link, class:"img-responsive" %> 
                    </div>
                    <%= render partial: 'shared/new_book_options', locals: {book: book} %>
                </div>
    
            </div><!-- end row -->
        </div>
        <div class="modal-body">
          <p><%=book.description%></p>
        </div>
      </div>
    </div>
</div>

app/views/books/edit.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= f.select :category_id, @categories   %>  
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<div class="jumbotron">
  <h1>Book-Keeper</h1>
  <p>Book Keeper allows you to track the books that you and your friends have read.  By using Google Books, it allows you to easily search and add books.  Never forget the books you've read again!</p>
  <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-lg btn-primary" %>

  
</div>

<h3 class="page-header">Recently Read Books</h3>

<div class="activity-section section">
  <% @books.each do |activity| %>
      <div class="col-md-8 col-md-offset-2">
          <div class="activity row ">
              <%= render partial: 'shared/activity', locals: {activity: activity} %>
          </div>
      </div>
  <% end %>
</div>
  

app/views/books/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
      <div class="section search-section">
          <% if !@searchBooks.nil? %>
              <% @searchBooks.each do |searchBook| %>
                  <div class="row search-book">
                      <div class="col-sm-4">
                          <%= image_tag searchBook.image_link, class: "book-show center-block" %> 
                          <a href="#book-<%=searchBook.isbn%>"></a>
                      </div>
                      <div class="col-sm-8">
                          <h4><%= searchBook.title %></h4>
                          <p>By <%= searchBook.authors_array.first %></p>
                          <p><%= truncate(searchBook.description, length:300)   %></p>
                          <%= render partial: 'shared/new_book_options', locals: {book: searchBook} %>
                      </div>
                  </div>
              <% end %> <!-- end iterate through search books -->
          <% end %><!-- searchBooks exist-->
      </div><!-- end search-section -->
  </div>
</div>

app/views/books/show.html.erb
<div class="book-show-section section">
    <div class="row book-detail-row">
        <%= render partial: 'shared/book_details', locals: {book: @book} %>
    </div>
    <hr>
    
    <div id="reviews-section">
        <% if @reviews.blank? %>
            <p>Be the first to review this book.</p>
        <% else %>
            <% @reviews.each do  |review| %>
                <%= render partial: 'review', locals: {review: review } %>
            <% end %>  
        <% end %>
    </div>
    
</div>
    
<script>
    $(document).ready(function() {
        $(".star-rating").raty({
            path: '/assets/',
            readOnly: true,
            score: function(){
                return $(this).attr('data-score');
            }
        });
    })
</script>