config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users

  get '/users/:id', to: 'users#show'
  get '/feed', to: 'users#feed'
  get '/friends', to: 'users#friends'
  get '/users', to: 'users#index'
  
  post '/follows', to: 'follows#create'
  delete '/follows', to: 'follows#destroy'

  root 'books#index'

  resources :books do
      resources :reviews, except: [:show, :index]
  end
  
  get '/about', to: 'about#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_book
  before_action :authenticate_user!


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.book_id = @book.id
    
    if @review.save
      flash[:success] = "Review successfully created"
      redirect_to @book
    else
      flash[:danger] = "Review not created"
      redirect_to @book
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if @review.update(review_params)
        flash[:success] = "Review successfully updated"
        redirect_to @book
      else
        flash[:danger] = "Review not updated"
        redirect_to @book 
      end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    flash[:success] = "Review successfully deleted"
    redirect_to @book

  end

  private
    def set_book
      @book = Book.find(params[:book_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :rating)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @review]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="field">
      <div class="star-rating">
      </div>
    </div>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>  

<script>
  $('.star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', book_review_path(@book, @review) %>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
      <h3 class="page-header">New Review</h3>
        <%= render 'form' %>
        
        <%= link_to 'Back', book_path(@book) %>
  </div>
</div